    <header >
        <img id="logo" src="images/zit.jpeg" alt="zitwh.jpeg" title="logo"/>
        <nav>
            <ul class="navigation">
                <li><a href="index.html">Home</a> | </li>
                <li><a href="jobs.html">Careers</a> |</li>
                <li><a href="apply.html">Apply</a> |</li>
                <li><a href="about.html">About Us</a> |</li>
                <li><a href="enhancements.html">Enhancements</a> |</li>
                <li><a href="enhancements2.html">Enhancements2</a> |</li>
                <li><a href="mailto:103501849@student.swin.edu.au" target="_blank">Get in touch</a>
            </ul>
        </nav>
    </header>